### ISSUE TITLE
Search doesn't do anything on pt.quarkus.io

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/pt.quarkus.io#117]
See https://github.com/quarkusio/ja.quarkus.io/issues/1104#issue-2093612677 : the same problem occurs on pt.quarkus.io, and most likely requires the same solution.

**Comment by ynojima** [comment]
@yrodiere Thank you for filing this issue. Allow me to add some more context.
Since `_includes/index-docs.html` and `_includes/index-guides.html` are updated in the upstream, 
`l10n/override/pt_BR/_includes/index-docs.html` and `l10n/override/pt_BR/_includes/index-guides.html` in this repository are outdated.
https://github.com/quarkusio/pt.quarkus.io/blob/main/l10n/stats/override.csv
As these files are not up-to-date, the new search feature in the https://pt.quarkus.io/guides/ page isn't working.

Please compare with files in upstream and pull changes in this way: https://github.com/quarkusio/ja.quarkus.io/pull/1106/files (ja.quarkus.io)
